;-----------------------------------------------------------------------
include     windows.inc
include     macros.asm
include     xmacros.mac

;-----------------------------------------------------------------------
includes    kernel32, user32, gdi32, advapi32, masm32, comctl32, ole32, oleaut32, winmm
includes    xcom.inc, xcom.def, misc\xsleep.asm, misc\xfill.asm, misc\xrand.asm
;-----------------------------------------------------------------------
