;-----------------------------------------------------------------------
include     windows.inc
include     macros.asm
include     xmacros.mac

;-----------------------------------------------------------------------
includes    kernel32, user32, gdi32, advapi32, comctl32, ole32, oleaut32, winmm
includes    resources.inc, core.inc, stub.inc, ufmod, xskin, slib, seh, crc32, md5, xcom, xlib

;-----------------------------------------------------------------------
