;-----------------------------------------------------------------------
IDI_MAIN        equ 100

IDB_HELP        equ 100
IDB_CLOSE       equ 101

IDD_MAIN        equ 200

IDE_SERIAL      equ 300
IDE_NAME        equ 301

IDR_MAIN        equ 399

IDR_EXITUP      equ 403
IDR_EXITDOWN    equ 404
IDR_EXITOVER    equ 405

IDR_ABOUTUP     equ 406
IDR_ABOUTDOWN   equ 407
IDR_ABOUTOVER   equ 408

IDR_MUSIC       equ 600
IDR_RGN         equ 601
IDR_INFO        equ 602

IDD_SCROLLER    equ 700
;-----------------------------------------------------------------------
